parameters:
- name: mySteps
  type: stepList
  default: []

jobs:
- jobs:
  steps: 
  - task: MyTelementryTask@1
    inputs:
      steps: 
      - ${{ each step in parameters.mySteps }}:
          - ${{ step }}
