version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - './data/db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
  web:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '.:/code'
    ports:
      - '8000:8000'
    depends_on:
      - db
      - mysql
